clc
clear all

syms L1 L2 L3 theta1 theta2 theta3 g


G_comp =[ 
 45*sin(theta3)*(g*cos(theta1)*sin(theta2) + g*cos(theta2)*sin(theta1)) - 75*g*cos(theta1) - 45*cos(theta3)*(g*cos(theta1)*cos(theta2) - g*sin(theta1)*sin(theta2)) - 30*sin(theta3)*(3*cos(theta3)*(g*cos(theta1)*sin(theta2) + g*cos(theta2)*sin(theta1)) + 3*sin(theta3)*(g*cos(theta1)*cos(theta2) - g*sin(theta1)*sin(theta2)) + 45*theta3^2) - 30*cos(theta2)*(sin(theta3)*(3*cos(theta3)*(g*cos(theta1)*sin(theta2) + g*cos(theta2)*sin(theta1)) + 3*sin(theta3)*(g*cos(theta1)*cos(theta2) - g*sin(theta1)*sin(theta2)) + 45*theta3^2) + cos(theta3)*(3*cos(theta3)*(g*cos(theta1)*cos(theta2) - g*sin(theta1)*sin(theta2)) - 3*sin(theta3)*(g*cos(theta1)*sin(theta2) + g*cos(theta2)*sin(theta1))) + 4*g*cos(theta1)*cos(theta2) - 4*g*sin(theta1)*sin(theta2)) - 30*sin(theta2)*(cos(theta3)*(3*cos(theta3)*(g*cos(theta1)*sin(theta2) + g*cos(theta2)*sin(theta1)) + 3*sin(theta3)*(g*cos(theta1)*cos(theta2) - g*sin(theta1)*sin(theta2)) + 45*theta3^2) - sin(theta3)*(3*cos(theta3)*(g*cos(theta1)*cos(theta2) - g*sin(theta1)*sin(theta2)) - 3*sin(theta3)*(g*cos(theta1)*sin(theta2) + g*cos(theta2)*sin(theta1))) + 4*g*cos(theta1)*sin(theta2) + 4*g*cos(theta2)*sin(theta1)) - 30*cos(theta3)*(3*cos(theta3)*(g*cos(theta1)*cos(theta2) - g*sin(theta1)*sin(theta2)) - 3*sin(theta3)*(g*cos(theta1)*sin(theta2) + g*cos(theta2)*sin(theta1))) - 60*g*cos(theta1)*cos(theta2) + 60*g*sin(theta1)*sin(theta2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  45*sin(theta3)*(g*cos(theta1)*sin(theta2) + g*cos(theta2)*sin(theta1)) - 45*cos(theta3)*(g*cos(theta1)*cos(theta2) - g*sin(theta1)*sin(theta2)) - 30*sin(theta3)*(3*cos(theta3)*(g*cos(theta1)*sin(theta2) + g*cos(theta2)*sin(theta1)) + 3*sin(theta3)*(g*cos(theta1)*cos(theta2) - g*sin(theta1)*sin(theta2)) + 45*theta3^2) - 30*cos(theta3)*(3*cos(theta3)*(g*cos(theta1)*cos(theta2) - g*sin(theta1)*sin(theta2)) - 3*sin(theta3)*(g*cos(theta1)*sin(theta2) + g*cos(theta2)*sin(theta1))) - 60*g*cos(theta1)*cos(theta2) + 60*g*sin(theta1)*sin(theta2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                45*sin(theta3)*(g*cos(theta1)*sin(theta2) + g*cos(theta2)*sin(theta1)) - 45*cos(theta3)*(g*cos(theta1)*cos(theta2) - g*sin(theta1)*sin(theta2))];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
tau_f = [- 10*L2*cos(theta1 + theta2) - 10*L1*cos(theta1) - 10*L3*cos(theta1 + theta2 + theta3);
                             - 10*L2*cos(theta1 + theta2) - 10*L3*cos(theta1 + theta2 + theta3);
                                                           -10*L3*cos(theta1 + theta2 + theta3)];                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
tau_G_f = G_comp+tau_f;
                                                 
G_sum = simplify(transpose(tau_G_f)*tau_G_f);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
dG_compdq1 = simplify(diff(G_sum,theta1));
dG_compdq2 = simplify(diff(G_sum,theta2));
dG_compdq3 = simplify(diff(G_sum,theta3));

dG_compdq(1,1) = dG_compdq1;
dG_compdq(2,1) = dG_compdq2;
dG_compdq(3,1) = dG_compdq3;